### ISSUE TITLE
LAB 17

### ISSUE THREAD

**Issue by UsingCoding** [IrinaRogacheva/basic_of_programming#1]
### 17.1

- [x] А тут как у вас, как говорится, лишняя проверка на EOLN
https://github.com/IrinaRogacheva/basic_of_programming/blob/eff01dedb81e9a7744095046c442b0826c6211cd/17.1.pas#L30

- [x] Эта инициализация избыточна
https://github.com/IrinaRogacheva/basic_of_programming/blob/eff01dedb81e9a7744095046c442b0826c6211cd/17.1.pas#L28

- Какая-то странная эквилибристика с открытием файла туда-сюда, если можете, то упростите. Это не как замечание, а скорее комментарий
https://github.com/IrinaRogacheva/basic_of_programming/blob/eff01dedb81e9a7744095046c442b0826c6211cd/17.1.pas#L17-L23

### 17.2

- По этому заданию замечаний нет, так что если исправите часть, заимстванную из первого задания, то будет зачтено

**Comment by UsingCoding** [comment]
### 17.3

- [x] Что за переменная `Q`, её название ни о чём не говорит
https://github.com/IrinaRogacheva/basic_of_programming/blob/b9b117a283953e03f88fd9db5f35fa16cc995f24/lw17/17.3.pas#L3

- [x] Вам не нужна эта часть вынесенная за цикл, оптимизируйте код и внесите эту часть в цикл. Но не прямо копипастой и стоит изюавиться от переменной N2, она лишняя определенно
https://github.com/IrinaRogacheva/basic_of_programming/blob/b9b117a283953e03f88fd9db5f35fa16cc995f24/lw17/17.3.pas#L56-L70

**Comment by IrinaRogacheva** [comment]
В таблице написано "принято", но здесь остались замечания.

**Comment by UsingCoding** [comment]
### 17.3

- [x] Есть ошибка форматирования

**Comment by UsingCoding** [comment]
> В таблице написано "принято", но здесь остались замечания.

Да, это моя ошибка, прошу прощения. Добавил ещё одно замечание, исправьте его

**Comment by IrinaRogacheva** [comment]
Убрала лишний ELSE в процедуре ReadDigit, в  процедуре ReadNumber добавила пробелы вокруг знака умножения, убрала скобки вокруг условия NOT Overflow. Надеюсь в этом списке есть та ошибка форматирования, которую вы имели ввиду)

**Comment by UsingCoding** [comment]
> Убрала лишний ELSE в процедуре ReadDigit, в процедуре ReadNumber добавила пробелы вокруг знака умножения, убрала скобки вокруг условия NOT Overflow. Надеюсь в этом списке есть та ошибка форматирования, которую вы имели ввиду)

Не замечание, а пометка: скобки вокруг `NOT Overflow` можно было не убирать, нои выделяли это условие среди других, из-за чего немного лучше была читаемость этого самого  условия
